### ISSUE TITLE
Is there an anyway to link with my system default python?

### ISSUE THREAD

**Issue by HighCWu** [touilleMan/godot-python#100]
Or with the Anaconda python?
I would like to use the python's packages I installed before.

**Comment by touilleMan** [comment]
Hi,
You cannot do that because Godot-Python ships with it very own interpreter.
However what you can do is to customize the PYTHONPATH configuration inside Godot allow it to load your packages (go to Project->Project settings->Python). This should work as long as your anaconda python is the same version as godot python (i.e. 3.6). This can work if it's not the same version but still Python3 except for binary packages.

**Comment by HighCWu** [comment]
TX.
It helps a lot.

**Comment by jejay** [comment]
I think this is very important. Using external python modules is the main selling point of this project in my opinion. I, for example, try to integrate numpy, scipy and tensorflow. Maybe it could be discussed in the README what the different options and benefits/downsides are.

**Comment by chrisgraf** [comment]
Maybe I am blind but i can not find Project -> Project Settings - >Python to set the PYTHON_PATH in the latest release (0.30.0). Could somebody maybe post a screenshot or point me there? thanks!

**Comment by touilleMan** [comment]
@chrisgraf 
![image](https://user-images.githubusercontent.com/3187637/81615783-74d17f00-93e2-11ea-8ddb-e583f1511a07.png)

It's the "Path" field, you should provide godot style path (i.e. res://foo/bar)

**Comment by chrisgraf** [comment]
@touilleMan : thanks for pointing me there - maybe it was already too late and my brain did not work that well anymore ;)

I would call it 'PYTHON_PATH' if this is really what it is. At least it triggers the eye of somebody who is familiar with Python

But that means that no external directory can be added and so you have to manually copy (as of #153  pip does not work currently, correct?) the library into your project?
