### ISSUE TITLE
Don't understand how to run the pong example

### ISSUE THREAD

**Issue by CryptoKR** [touilleMan/godot-python#187]
I have cloned the repository and followed the build instructions. 

After following the instructions on running the example project:
$ scons platform=x11-64 example

I get:
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `example' is up to date.
scons: done building targets.

I am not sure how to run the pong example. I imported the pong example in my godot editor and played it (F5), but i get a bunch of load errors:

E 0:00:00.185   open_dynamic_library: Can't open dynamic library: /home/kr/Downloads/godot-python/examples/examples/pong/pythonscript/x11-64/libpythonscript.so. Error: /home/kr/../lib/libpythonscript.so: cannot open shared object file: No such file or directory
  <C++ Error>   Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <C++ Source>  drivers/unix/os_unix.cpp:424 @ open_dynamic_library()

What must I do to get the pong example running? I don't understand how it works.

**Comment by CryptoKR** [comment]
When I explore the scenes in godot, I also get errors that I am unable to load the python script dependencies for the nodes. Example, Error loading ball.tscn - load failed due to missing dependencies res://ball.py. 

Does it mean I did not install godot-python properly?

**Comment by CryptoKR** [comment]
I get this error when opening the pong project in godot. 

![Screenshot at 2020-05-25 00-55-45](https://user-images.githubusercontent.com/37015566/82759880-9723bd80-9e22-11ea-9cb1-18efe1509746.png)

**Comment by touilleMan** [comment]
Hi,

It seems the `scons example` rule was broken, I've fixed it with 4782460

Note the reason you cannot just jump into `examples/pong` folder and run godot from there is the scons rule creates a symbolic link examples/pong/pythonscript -> build/dist/pythonscript

**Comment by CryptoKR** [comment]
hmm, I don't understand the "just jump into examples/pong and run godot" part. 

So everytime I want to run the game pong or anyother godot-python project, I must use scons platform=x11-64 example, instead of using the godot editor?

**Comment by touilleMan** [comment]
@CryptoKR when you have a traditional godot project (with no godot-python stuff), you go into the project directory and run `godot` (or do `godot --path=<path_to_the_project>`)

However this doesn't work on the `examples/pong` project (and on all other projects in the repo) because this project makes reference to `examples/pong/pythonscript` folder which doesn't exists
https://github.com/touilleMan/godot-python/blob/47824604b81c93a8cd84860edf44292b04b21baf/examples/pong/pythonscript.gdnlib#L9

This is because this folder should contain the godot-python build stuff (so a CPython interpreter and a libpythonscript.so that should be loaded by godot).
We cannot just put a symlink in the repo because it is not compatible with windows (where you have to use reparse point which are weird symlink that works only on folder).
So the solution is to create the symlink/reparse point lazily just before running the example
https://github.com/touilleMan/godot-python/blob/47824604b81c93a8cd84860edf44292b04b21baf/examples/SConscript#L4-L7

So obviously this means you can run `scons examples/pong` a single time, then uses `godot --path examples/pong` (given the symlink and build has now been created)
