### ISSUE TITLE
Build error: No module named 'dataclasses'

### ISSUE THREAD

**Issue by WilliamTambellini** [touilleMan/godot-python#219]
Just a minor build error : 

$ python3.6 -m venv venv36
$ . ./venv36/bin/activate
$ pip install -r requirements.txt
$ scons platform=x11-64 release 
scons: Reading SConscript files ...
3.6.11 (default, Jun 29 2020, 05:15:03) 
[GCC 5.4.0 20160609]
scons: done reading SConscript files.
scons: Building targets ...
python /home/wtambellini/repos/godot-python/tools/generate_bindings.py -i godot_headers/api.json -o build/x11-64/pythonscript/godot/bindings.pyx
Traceback (most recent call last):
  File "/home/wtambellini/repos/godot-python/tools/generate_bindings.py", line 9, in <module>
    from dataclasses import dataclass, replace
ModuleNotFoundError: No module named 'dataclasses'
scons: *** [build/x11-64/pythonscript/godot/bindings.pyx] Error 1
scons: building terminated because of errors.

Looks like dataclasses has just been forgotten from requirements.txt

if added to requirements:
...
Collecting dataclasses (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/e1/d2/6f02df2616fd4016075f60157c7a0452b38d8f7938ae94343911e0fb0b09/dataclasses-0.7-py3-none-any.whl

**Comment by touilleMan** [comment]
You're right, I've started to use dataclasses which requires at least Python 3.7 while the project documentation states that Python 3.6 is supported !

As you pointed out this is easily fixable by installing the backport version (I should also correct the CI to use Python 3.6 in order to ensure this kind of compatibility issues won't happen again ^^)

**Comment by touilleMan** [comment]
see #223

**Comment by touilleMan** [comment]
fixed by #224
