### ISSUE TITLE
What data (types) can be passed between Godot and Python, and how can they be passed?

### ISSUE THREAD

**Issue by thetoblin** [touilleMan/godot-python#246]
I'm having troubles understanding what data types can be passed from Godot to Python and vice versa. My main goal of using Python is to 1) pass some data from Godot to Python, 2) let Python process the data, and 3) return some data back to Godot.

**Godot array -> Python**
```
# In Godot
var PythonNetwork     = load("res://network.py")
var python_network    = PythonNetwork.new()
print("python_network.b = ", python_network.b)
python_network.b = [1,2,3,4]
print("python_network.b = ", python_network.b)
```

Gives output:
```
python_network_node.b = Null
python_network_node.b = [1, 2, 3, 4]
```
So I'm able to pass an Array from Godot to Python. 

**Python array -> Godot**
But when I try to change the value of `b` in python, I get a warning in addition to it not working. Running the following in Godot:
```
	python_network.test()    # changes the value of b inside the python script. See below
	print("python_network_node.b = ", python_network.b)
```
gives the output
```
sys:1: UserWarning: Cannot convert `<class 'list'>` to Godot's Variant
python_network_node.b = Null
```

Here is the python script:
```
# Python script with attribute b that is changed
from godot import exposed, export
from godot import *

@exposed
class network(Node):
	a = 0.0
	b = []

	def _ready(self):
		pass

	def test(self):
		b = [1,1,1,1]  # <-------- value of b is changed in this method
```

**Question**
What can I pass Godot->Python and Python->Godot? Is it supported at current time to pass more complex data (except for floats, bool, etc) such as an array or similar between the two?

What is the intended way of passing data between Godot and Python (if any)?

A related issue https://github.com/touilleMan/godot-python/issues/96 says that it is not possible to pass arrays from Python->Godot. Any suggestions on how to proceed in that case?

**Comment by touilleMan** [comment]
As you discovered, you can only pass Godot types between Godot and Python.
when building a list the python way (i.e. `b = [1, 1, 1, 1]`) you create a Python list, however you are supposed to transmit a Godot list (called an array in GDScript).
So you have to convert your python list into a Godot one: `b = godot.Array([1, 1, 1, 1])`

To be honest I'm not sure this "never do automatic Python<->Godot types conversion" behavior is that good (see #188 )

btw, you are supposed to use the `export` function on your class attribute to indicate they are exposed accessible from Godot:
```python
@exposed
class network(Node):
    a = export(float)
    b = export(godot.Array)
```

Beside, the `b = [...]` in you test method should be `self.b = [...]` otherwise you're just creating a local variable named `b` instead of modifying the class attribute.

**Comment by thetoblin** [comment]
I think I'm ready to close this issue. My initial question was a bit broad to begin with, but for my applications I've gotten what I need I think.

One question: is there any difference between using `export` and not using it? Except for clarity in code.

**Comment by touilleMan** [comment]
`export` declares the variable to be accessible from Godot (you can see&edit it in the GUI)
