### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by finchMFG** [touilleMan/godot-python#25]
Hey there! I'm trying to incorporate a tensor-flow chat bot but am getting this error when I run the scene:

```
  File "/media/ecludian/Data/GameDev/Godot/godot-python-0.9.0/lib/python36.zip/bz2.py", line 23, in <module>
ModuleNotFoundError: No module named '_bz2'
```

Is there anyway to add support for bz2? Cheers!

**Comment by touilleMan** [comment]
Thanks for the issue !
It turns out I didn't compile CPython with the optional dependencies, hence this missing .so

Quick fix here: Unzip this archive and replace your `lib/python3.6/lib-dynload` folder with it
[lib-dynload.zip](https://github.com/touilleMan/godot-python/files/1150200/lib-dynload.zip)

I'll make sure next release won't have this trouble ;-)

btw your project seems great, make sure to keep in touch

**Comment by finchMFG** [comment]
Cheers, that solved it! And thanks can do :)
