### ISSUE TITLE
Tensorflow Lite with godot from conda's repositories.

### ISSUE THREAD

**Issue by MintStudios** [touilleMan/godot-python#271]
Hello,
I've been trying to find a way to make a mobile app with tensorflow, but it's kinda hard to find something that is easy to incorporate into my workflow. I'm familiar with godot and python, and I'd want to get tensorflow working with my project.
Now, for the builds of tensorflow compatible with mobile devices, I think I might have found a solution to get it working with iOS devices.
[Anaconda/Miniconda has builds for the new M1 macs with the ARM architecture](https://github.com/apple/tensorflow_macos/issues/3#issuecomment-753425933). Now, these builds can install native tensorflow, numpy, **and** scipy.
Would there be a way to take these builds and use them in a project?

I'm just throwing ideas out, so if there is an easy way to get tensorflow in my project, I'd love that.

(Also, I'm just going to be using python to communicate with the model, and GDScript for the rest.)

**Comment by touilleMan** [comment]
Hi @MintStudios 

> I've been trying to find a way to make a mobile app with tensorflow

Long story short: Python on Android is a pain, Python with binary modules on Android is a nightmare, adding Godot in the equation is going to be an order of magnitude worst :'-(

> Anaconda/Miniconda has builds for the new M1 macs with the ARM architecture

Godot-Python doesn't have build for the new M1 architecture (I don't know where Godot is itself on this topic)
I would guess however that the new M1 architecture is not compatible with the iOS architecture so you 

> I'm just throwing ideas out, so if there is an easy way to get tensorflow in my project, I'd love that.

Mobile architecture are really exotic ecosystem (this is a fancy way to say people designing those system have seriously screw up due to time to market concern and NIH syndrome, and now millions of devs like you and me have to suffer :trollface: ).
Every time you try to combine two exotic things, you shrink the amount of documentation/examples/existing stuff.
So the only viable solution is to deal with exotic systems one at a time:
- Android + Tensorflow 
- Android + Godot
- Android + native interfacing
- Godot+ native interfacing

The idea here is to first make Tensorflow working on Android (see for instance [here](https://www.tensorflow.org/lite/guide/android), given it's on the Tensorflow website you should be confident enough about it ^^)
Then make Godot work on Android, this is already a supported platform so it should be simple enough (https://docs.godotengine.org/fr/stable/getting_started/workflow/export/exporting_for_android.html)
And finally do the interfacing between Godot and Tensorflow _through_ Android.

As you can see, there is no space for Python here given it would add another exotic system and hence add complexity ;-)
