### ISSUE TITLE
VSCode, Geany: Unable to import 'godot' module

### ISSUE THREAD

**Issue by ka23ppa3** [touilleMan/godot-python#298]
VSCode pylint, Geany and possibly others editors seems to be not able to recognize and find reference to godot module which is most basic for any game script.

How to reproduce:
1) Create or open project
2) Set VSCode as external code editor
3) Create and open script
4) Import godot module and you are here...

Even VSCode addon "Godot Tools" does not helped in this situation.

**Comment by touilleMan** [comment]
`godot` modules is located in `addons/pythonscript/windows-64/Lib/site-packages/`, it should be already part of the PYTHONPATH of the embedded python interpreter:
```
$ .\build\dist\addons\pythonscript\windows-64\python.exe
Python 3.8.5 (default, Aug 30 2020, 16:01:16) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'C:\\Users\\gbleu\\source\\repos\\godot-python\\godot-python\\build\\dist\\addons\\pythonscript\\windows-64\\python38.zip', 'C:\\Users\\gbleu\\source\\repos\\godot-python\\godot-python\\build\\dist\\addons\\pythonscript\\windows-64\\DLLs', 'C:\\Users\\gbleu\\source\\repos\\godot-python\\godot-python\\build\\dist\\addons\\pythonscript\\windows-64\\lib', 'C:\\Users\\gbleu\\source\\repos\\godot-python\\godot-python\\build\\dist\\addons\\pythonscript\\windows-64', 'C:\\Users\\gbleu\\AppData\\Roaming\\Python\\Python38\\site-packages', 'C:\\Users\\gbleu\\source\\repos\\godot-python\\godot-python\\build\\dist\\addons\\pythonscript\\windows-64\\lib\\site-packages']
```

So you should indicate to VSCode the python interpreter you want to use (see `Python: Select Interpreter` option in VSCode Python extension).
You cannot import the `godot` module from the python interpreter (this is because `godot` module connects with Godot game engine, is it can be used only if the Python interpreter has been initialized from the Godot game engine):
```
$ .\build\dist\addons\pythonscript\windows-64\python.exe
Python 3.8.5 (default, Aug 30 2020, 16:01:16) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import godot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gbleu\source\repos\godot-python\godot-python\build\dist\addons\pythonscript\windows-64\lib\site-packages\godot\__init__.py", line 8, in <module>
    raise ImportError(
ImportError: Cannot initialize godot module given Godot GDNative API not available.
This is most likely because you are running code from a regular Python interpreter (i.e. doing something like `python my_script.py`) while godot module is only available to Python code loaded from Godot through Godot-Python plugin.
```

However this should be fine given code completion only does static analysis (so reading .py and .pyi files to determine the structure of the code).

I don't have much experience with auto-complete integration with VSCode & other IDE, so don't hesitate to give feedback on this here ;-)

**Comment by ka23ppa3** [comment]
Hello, thanks for the reply. Im using VSCode and Godot on gnu/linux so maybe there is can be some difference. I changed ```Python: Default Interpreter Path``` to ``` addons/pythonscript/x11-64/bin/python3.8 ``` but I see absolutely no difference after it. Auto-completion still not work for godot modules and same import-errors still popup.

**EDIT:** I will leave upper part for the history and other newbies, so lets go to solution.
**SOLUTION:** https://stackoverflow.com/questions/47602151/how-to-change-interpreter-in-visual-studio-code
Thanks!

**Comment by ka23ppa3** [comment]
You can solve it in Geany by changing interpreter in BUILD >> Set Build Commands, by default it will be:
```
python -m py_compile "%f"
```
and
```
python "%f"
```
so you need to write absolute path to addons/pythonscript/x11-64/bin/python3.8 if you are on Linux

Now Im closing this issue!
