### ISSUE TITLE
Getting status of official support in Godot

### ISSUE THREAD

**Issue by sHaggYcaT** [touilleMan/godot-python#325]
First, thanks for amazing project! How can I donate for it ;)?
I always wanted to do GameDev just for fun, and to improve my coding skills. Because I'm infrastructure/cloud developer, I don't need c#
So, I waited until any engine start to support python or Golang (which is only two on-demand languages in computer cloud industry outside of MS Azure). Panda3D looks like outdated and even dying. And Godot is really cool, but GDscript is not Python, and after coding in it, my Python code(which I write because it's my current occupation, me, like everybody, need money to live...), could become worse. 
But this project, unfortunately, is unofficial.  Is it any chance, that once it becomes Godot's standard scripting language, like GDscript, C#, C++, and "visual scripting"? Any attempts to ask Godot community to do this?

**Comment by touilleMan** [comment]
> Is it any chance, that once it becomes Godot's standard scripting language

Sorry, the Godot dev team made this clear that there is zero chance for that 😄 

I understand that Python is appealing from a user point of view (that's why I started Godo-Python after all !), but from the Godot dev team, GDScript is a very good tool considering it deep integration within Godot (see https://docs.godotengine.org/en/stable/about/faq.html#what-is-gdscript-and-why-should-i-use-it)

If anything, this project has proved how complicated it is to integrate Python with Godot (it's doable but a lot more complicated than what is GDScript, without supporting things like mobile platform and web which comes free when using GDScript ^^)

**Comment by touilleMan** [comment]
Thanks for the offer, but this project is a hobby so I cannot provide professional support for it and hence don't accept donation ;-)

**Comment by sHaggYcaT** [comment]
How do you think, is it good enough to write using it just for fun games? :(
