### ISSUE TITLE
Collision with new OpenSSL package

### ISSUE THREAD

**Issue by kobi666** [touilleMan/godot-python#34]
When running  run_godot.sh,
the following error occurs when  openssl version is newer than 1.0.0:

/home/centos/Desktop/godot-python-0.9.0/godot.x11.opt.tools.64.llvm: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by touilleMan** [comment]
Hi, thanks for the issue

As you guessed, the release has been compiled with openssl 1.0 ([1.0.2g](https://packages.ubuntu.com/xenial/libssl1.0.0) to be precise) , so it is not compatible with newer version :'-(
Anyway, the bug I see is we should ship with a dedicated openssl (same for other 3rd party library like libbz2 for instance) instead of relying on the system one.

As you might know, I currently working with the Godot team to allow GDnative to directly load .so, which would allow to use godot-python with an official godot build.
This will easier a lot the build process, so I'm not planning on releasing any other version before that.

One solution in the meantime, would be to recompile your own version of Python 3.6 and replace the `libpython3.6m.so.1.0` in the release folder.

**Comment by touilleMan** [comment]
fixed now that we use python-standalone-build
