### ISSUE TITLE
Provide a python WHL for godot ?

### ISSUE THREAD

**Issue by stuaxo** [touilleMan/godot-python#35]
It would be great if godot-python could be installed with pip - this would be the most accessible way for python devs to gt godot.

Similar to Panda3D, this would need the build process to adds the godot libraries + any third party libs into the WHL.

**Comment by touilleMan** [comment]
I don't currently see a right way to provide Godot through pip given it embed it own python interpreter instead of relying on the default one.
Beside this would mean having to support the release of Godot versions which is a heavy burden (big project with native code, multiple platforms) that is already provided by the original Godot team.

So right now the goal to is to this the other way around: user download Godot, then user the godot asset store to install the godot-python plugin. Once this is done, he can use the pip provided by the plugin to install python packages.

**Comment by stuaxo** [comment]
It's a shame there is no way to use it from an external interpreter, since I'm not sure how you install libraries etc into an embedded python interpreter.    Thanks for the info :)

**Comment by touilleMan** [comment]
> since I'm not sure how you install libraries etc into an embedded python interpreter

The embedded interpreter behave just like a virtualenv: it provides you a pip command which will install the packages in it local directory and every works as expected ;-)

**Comment by stuaxo** [comment]
That is awesome :)

Also, thanks for the effort on bringing godot to python, the more decent game engines available from python the better.
