### ISSUE TITLE
GDExtension

### ISSUE THREAD

**Issue by ShalokShalom** [touilleMan/godot-python#398]
Which API does this project using? 

I do care for a list of projects, that provide language support to Godot. 
It is one of our goals, to include the information about the used API. 

https://github.com/Vivraan/godot-lang-support

**Comment by touilleMan** [comment]
Hi @ShalokShalom 

> Which API does this project using?

Both !

The Godot 3 version (i.e. the extension [available on the asset store](https://godotengine.org/asset-library/asset/179), which code is on the master branch) uses the old GDNative API

The work-in-progress Godot 4 version uses the new GDExtension API.

In a nutshell:
- the Godot 3 version on the extension works great (it main missing features are: 1) only Linux/Windows/MacOS are supported, and 2) Godot's integrated export feature is not supported)
- the Godot 4 version is a full rewrite due to the change in Godot API (and the work is slow and tricky given I don't have much time right now and GDExtension powerfulness comes from the fact it is very low-level and complex to use ^^)

**Comment by pizzapi2012** [comment]
> Hi @ShalokShalom
> 
> > Which API does this project using?
> 
> Both !
> 
> The Godot 3 version (i.e. the extension [available on the asset store](https://godotengine.org/asset-library/asset/179), which code is on the master branch) uses the old GDNative API
> 
> The work-in-progress Godot 4 version uses the new GDExtension API.
> 
> In a nutshell:
> 
> * the Godot 3 version on the extension works great (it main missing features are: 1) only Linux/Windows/MacOS are supported, and 2) Godot's integrated export feature is not supported)
> * the Godot 4 version is a full rewrite due to the change in Godot API (and the work is slow and tricky given I don't have much time right now and GDExtension powerfulness comes from the fact it is very low-level and complex to use ^^)

are u working on it?!
