### ISSUE TITLE
Getting Started??

### ISSUE THREAD

**Issue by ranjian0** [touilleMan/godot-python#53]
Its not clear how we are supposed to use this. The readme file only explains how to build from source.

I have godot 3.0 installed and downloaded the latest release of this project.

How do I set up the library in my project?

**Comment by deep-gaurav** [comment]
It's easy. Do not rely on godot-python release, it's a little outdated and gdnative api changed since., do what is compile it, and in build folder you'll have a directory named something like "x11-pypy", just copy it's content to the root of your project, if project is already opened in Godot, close and reopen Godot(not really needed but still), and that's it, you'll now have the option to choose python in add script.,

**Comment by leotada** [comment]
@deep-gaurav I could not do it too.

**Comment by ranjian0** [comment]
Thanks, this instructions should be on in the readme file.
