### ISSUE TITLE
Can't build against latest gdnative headers in godot repo

### ISSUE THREAD

**Issue by garyo** [touilleMan/godot-python#80]
I don't know if this is supposed to work, but I tried building godot-python using the latest 3ad9e4740 godot, using its gdnative headers and wrapper lib directly, and it doesn't build on Windows.
Here's the scons command I used:
```scons -j16 platform=windows-64 backend=cpython godot_binary=../godot/bin/godot.windows.opt.tools.64.exe MSVC_USE_SCRIPT=True gdnative_include_dir=../godot/modules/gdnative/include gdnative_wrapper_lib=../godot/bin/gdnative_wrapper_code.windows.opt.tools.lib```
The errors are these:
```
link /nologo /dll /out:pythonscript\pythonscript.dll /implib:pythonscript\pythonscript.lib /LIBPATH:platforms\windows-64\cpython\PCBuild\amd64 python36.lib ../godot/bin/gdnative_wrapper_code.windows.opt.64.lib pythonscript\pythonscript.obj pythonscript\cffi_bindings.gen.obj
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_set_method_argument_information referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_set_class_documentation referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_set_method_documentation referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_set_property_documentation referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_set_signal_documentation referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_set_global_type_tag referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_get_global_type_tag referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_set_type_tag referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_get_type_tag referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_register_instance_binding_data_functions referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_unregister_instance_binding_data_functions referenced in function _cffi_start_python
cffi_bindings.gen.obj : error LNK2019: unresolved external symbol godot_nativescript_get_instance_binding_data referenced in function _cffi_start_python
pythonscript\pythonscript.dll : fatal error LNK1120: 12 unresolved externals```

It builds fine without using the `gdnative_include_dir=...` arg, so feel free to close this issue if this isn't expected to work.

**Comment by touilleMan** [comment]
I feel like I already encountered this `unresolved externals` error a while ago...
https://github.com/godotengine/godot/issues/12849 seems to suggest this is due to a visual studio update.

Out of this, doing a `diff -r godot-python/platforms/gdnative/include/ godot/modules/gdnative/include/  | grep -ve '/\*' | less` shows really few changes between Godot-python's and Godot 3.0.2's gdnative includes.
I've build with problems Godot-python with Godot 3.0.2 include headers on linux so my guess is it's a toolchain issue.

**Comment by touilleMan** [comment]
Yep, it seems I've discarded the API addition too quickly when looking the diff ^^
Have you tried to replace the current includes in `platforms/GDnative/include` by the up to date one from Godot 3.0.2 ?
Not this is something we want to do (because it would mean we are no longer compatible with Godot 3.0), but it would narrow the trouble

**Comment by touilleMan** [comment]
Ho ! I reread your original issue and realised the trouble actually comes from what I suggest !
We'll want you can do is use the Godot 3.0 headers but link against the 3.0.2 wrapper lib.

Anyway this link error is a bit sad because the whole point of GDnative API being divided in pointer-linked structures was to allow painless backward compatibility :'-(

**Comment by garyo** [comment]
So what's the next step for this? Is there something core godot should do to prevent the new header functions from "leaking" into the API? Or should gdnative do something to account for the new 1.1 functions? I don't understand the GDnative structure well enough to know where it should be fixed (if anywhere).

**Comment by touilleMan** [comment]
So in the end I guess we should close this issue and accept we should stick with the Godot 3.0 headers that have been copied in the project,  and which will be updated if we decide to support further API changes.

Obviously this means we couldn't provide optional support for the GDnative api extensions, but I would rather wait for the need to come before doing something about this ;-)

**Comment by aaronfranke** [comment]
Is this still the case with Godot 3.2.3 headers? I'm having the same problem, there's a lot of symbols it can't resolve.

**Comment by touilleMan** [comment]
Hi @aaronfranke ;-)

> there's a lot of symbols it can't resolve.

Is it during the runtime of a project using Godot-Python or during compilation of the Godot-Python plugin ?
Can you provide the version of Godot, Godot-Python and `godot_headers` you were using ? (and also some logs of your issues)

Godot-Python architecture and Godot GDnative have changed  quiet a bit since this issue:
- the `gdnative_wrapper_code` library has been deprecated and is no longer used (this issue was complaining about this particular)
- Godot-Python generates it bindings from the `gdnative_api.json` and `api.json` files provided by the `godot_headers` folder (before that, their was some code generated by hand so there could be some desynchronization between `godot_headers` and Godot-Python codebase)

So in theory compilation should run fine (except if you try to compile against a very old version of `godot_headers` !)

For the runtime part, there is no check in Godot-Python to ensure the version of Godot running is compatible with the `godot_headers` that have been used (this is something we may want to add to avoid this kind of issues...)

As you've noticed the project relies on Godot 3.2.3 headers (`godot_headers` folder is a git submodule on https://github.com/godotengine/godot-headers/tree/815f34e1e96c09122449105c55aba501654da029).

So if you use another version of Godot you might encounter hiccups. If you are compiling Godot-Python, you should try to change the `godot_headers` code to the correct version.

Note there is there is discussion under way to improve the plugin/godot compatibility, but it most likely won't be available before Godot 4:
- https://github.com/godotengine/godot-proposals/issues/1613
- https://github.com/godotengine/godot/issues/35467#issuecomment-714362073
